CREATE TABLE IF NOT EXISTS countries (
  id BIGINT UNSIGNED PRIMARY KEY DEFAULT UUID_SHORT(),
  name VARCHAR (100) UNIQUE NOT NULL,
  alpha2 VARCHAR (3) NULL,
  alpha3 VARCHAR (4) NULL,
  phone_code VARCHAR (5) NULL,
  currency_code VARCHAR (5) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS industries (
  id BIGINT UNSIGNED PRIMARY KEY DEFAULT UUID_SHORT(),
  name VARCHAR (100) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ranks (
  id BIGINT UNSIGNED PRIMARY KEY DEFAULT UUID_SHORT(),
  name VARCHAR (100) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS work_functions (
  id BIGINT UNSIGNED PRIMARY KEY DEFAULT UUID_SHORT(),
  name VARCHAR (100) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS experience_levels (
  id BIGINT UNSIGNED PRIMARY KEY DEFAULT UUID_SHORT(),
  name VARCHAR (100) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS project_categories (
  id BIGINT UNSIGNED PRIMARY KEY DEFAULT UUID_SHORT(),
  name VARCHAR (100) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL
);
