
version: "3.7"
services:
    mariadb:
        image: mariadb:10.4.13
        container_name: mariadb-server
        command: --max-allowed-packet=67108864 --local-infile=0 --sql-mode="STRICT_ALL_TABLES"
        volumes:
            - mariadb-data:/var/lib/mysql
        ports:
            - "3306:3306/tcp"
        environment:
            - MYSQL_ROOT_PASSWORD=mariadb
            - MYSQL_DATABASE=osslocal_keycloak
            - MYSQL_USER=mariadb
            - MYSQL_PASSWORD=mariadb
        networks:
            - sesame-graph          
    keycloak:
        image: jboss/keycloak:10.0.1
        container_name: keycloak-server
        command: -Dkeycloak.migration.strategy=IGNORE_EXISTING
        ports:
            - "8080:8080"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_VENDOR=mariadb
            - DB_ADDR=mariadb-server
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=mariadb            
            - DB_DATABASE=osslocal_keycloak 
        cap_drop:
            - ALL
        cap_add:
            - NET_BIND_SERVICE           
        depends_on:
            - mariadb
        networks:
            - sesame-graph
    phabricator:
        image: phabricator:1.0.0
        container_name: phabricator-server
        ports:
            - "80:80/tcp"
            - "443:443/tcp"
        environment:
            - PHABRICATOR_HOST=192.168.99.100
            - MYSQL_USER=root
            - MYSQL_PASS=mariadb
            - MYSQL_HOST=mariadb-server
            - MYSQL_PORT=3306
            - MYSQL_STORAGE_NAMESPACE=osslocal
            - KEYCLOAK_HOST=192.168.99.100:8080
            - KEYCLOAK_SSL=no
        depends_on: 
            - mariadb
        networks:
            - sesame-graph
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq-server
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - sesame-graph
    mailcatcher:
        image: mailcatcher:0.7.1
        container_name: mailcatcher-server
        ports:
            - "1025:1025"
            - "1080:1080"
        networks:
            - sesame-graph
            
networks:
    sesame-graph:

volumes:
    mariadb-data:
